import os

CURR_FILE_PATH = os.path.dirname(os.path.realpath(__file__))
STATIC_FILE_FOLDER_NAME = "static"
STATIC_FILE_FOLDER_PATH = os.path.join(CURR_FILE_PATH, STATIC_FILE_FOLDER_NAME)
PREREQUISITES_FOLDER_NAME = "prerequisites"
PREREQUISITES_FOLDER_PATH = os.path.join(CURR_FILE_PATH, PREREQUISITES_FOLDER_NAME)

FFMPEG_EXE_NAME = "ffmpeg.exe"
# FFPROBE_EXE_NAME = "ffprobe.exe"
FFMPEG_FOLDER_NAME = "ffmpeg"
FFMPEG_FOLDER_PATH = os.path.join(PREREQUISITES_FOLDER_PATH, FFMPEG_FOLDER_NAME)
FFMPEG_EXE_PATH = os.path.join(FFMPEG_FOLDER_PATH, FFMPEG_EXE_NAME)

os.environ["PATH"] += os.pathsep + FFMPEG_FOLDER_PATH

DEFAULT_SILENCE_DBFS = -64
